const symptoms = [
  { value: "itching", label: "Itching" },
  { value: "skin_rash", label: "Skin Rash" },
  { value: "continuous_sneezing", label: "Continuous Sneezing" },
  { value: "shivering", label: "Shivering" },
  { value: "stomach_pain", label: "Stomach Pain" },
  { value: "acidity", label: "Acidity" },
  { value: "vomiting", label: "Vomiting" },
  { value: "indigestion", label: "Indigestion" },
  { value: "muscle_wasting", label: "Muscle Wasting" },
  { value: "patches_in_throat", label: "Patches In Throat" },
  { value: "fatigue", label: "Fatigue" },
  { value: "weight_loss", label: "Weight Loss" },
  { value: "sunken_eyes", label: "Sunken Eyes" },
  { value: "cough", label: "Cough" },
  { value: "headache", label: "Headache" },
  { value: "chest_pain", label: "Chest Pain" },
  { value: "back_pain", label: "Back Pain" },
  { value: "weakness_in_limbs", label: "Weakness In Limbs" },
  { value: "chills", label: "Chills" },
  { value: "joint_pain", label: "Joint Pain" },
  { value: "yellowish_skin", label: "Yellowish Skin" },
  { value: "constipation", label: "Constipation" },
  {
    value: "pain_during_bowel_movements",
    label: "Pain During Bowel Movements",
  },
  { value: "breathlessness", label: "Breathlessness" },
  { value: "cramps", label: "Cramps" },
  { value: "weight_gain", label: "Weight Gain" },
  { value: "mood_swings", label: "Mood Swings" },
  { value: "neck_pain", label: "Neck Pain" },
  { value: "muscle_weakness", label: "Muscle Weakness" },
  { value: "stiff_neck", label: "Stiff Neck" },
  { value: "pus_filled_pimples", label: "Pus Filled Pimples" },
  { value: "burning_micturition", label: "Burning Micturition" },
  { value: "bladder_discomfort", label: "Bladder Discomfort" },
  { value: "high_fever", label: "High Fever" },
  { value: "nodal_skin_eruptions", label: "Nodal Skin Eruptions" },
  { value: "ulcers_on_tongue", label: "Ulcers On Tongue" },
  { value: "loss_of_appetite", label: "Loss Of Appetite" },
  { value: "restlessness", label: "Restlessness" },
  { value: "dehydration", label: "Dehydration" },
  { value: "dizziness", label: "Dizziness" },
  { value: "weakness_of_one_body_side", label: "Weakness Of One Body Side" },
  { value: "lethargy", label: "Lethargy" },
  { value: "nausea", label: "Nausea" },
  { value: "abdominal_pain", label: "Abdominal Pain" },
  { value: "pain_in_anal_region", label: "Pain In Anal Region" },
  { value: "sweating", label: "Sweating" },
  { value: "bruising", label: "Bruising" },
  { value: "cold_hands_and_feets", label: "Cold Hands And Feets" },
  { value: "anxiety", label: "Anxiety" },
  { value: "knee_pain", label: "Knee Pain" },
  { value: "swelling_joints", label: "Swelling Joints" },
  { value: "blackheads", label: "Blackheads" },
  { value: "urine", label: "Urine" },
  { value: "skin_peeling", label: "Skin Peeling" },
  { value: "blister", label: "Blister" },
  { value: "patches", label: "Patches" },
  { value: "watering_from_eyes", label: "Watering From Eyes" },
  { value: "extra_marital_contacts", label: "Extra Marital Contacts" },
  { value: "diarrhoea", label: "Diarrhoea" },
  { value: "loss_of_balance", label: "Loss Of Balance" },
  {
    value: "blurred_and_distorted_vision",
    label: "Blurred And Distorted Vision",
  },
  { value: "altered_sensorium", label: "Altered Sensorium" },
  { value: "dark_urine", label: "Dark Urine" },
  { value: "swelling_of_stomach", label: "Swelling Of Stomach" },
  { value: "bloody_stool", label: "Bloody Stool" },
  { value: "obesity", label: "Obesity" },
  { value: "hip_joint_pain", label: "Hip Joint Pain" },
  { value: "movement_stiffness", label: "Movement Stiffness" },
  { value: "spinning_movements", label: "Spinning Movements" },
  { value: "scurring", label: "Scurring" },
  { value: "continuous_feel_of_urine", label: "Continuous Feel Of Urine" },
  { value: "silver_like_dusting", label: "Silver Like Dusting" },
  { value: "red_sore_around_nose", label: "Red Sore Around Nose" },
  { value: "Symptom", label: "Symptom" },
  { value: "urination", label: "Urination" },
  { value: "passage_of_gases", label: "Passage Of Gases" },
  { value: "irregular_sugar_level", label: "Irregular Sugar Level" },
  { value: "family_history", label: "Family History" },
  { value: "lack_of_concentration", label: "Lack Of Concentration" },
  { value: "excessive_hunger", label: "Excessive Hunger" },
  { value: "yellowing_of_eyes", label: "Yellowing Of Eyes" },
  { value: "distention_of_abdomen", label: "Distention Of Abdomen" },
  { value: "irritation_in_anus", label: "Irritation In Anus" },
  { value: "swollen_legs", label: "Swollen Legs" },
  { value: "painful_walking", label: "Painful Walking" },
  { value: "small_dents_in_nails", label: "Small Dents In Nails" },
  { value: "yellow_crust_ooze", label: "Yellow Crust Ooze" },
  { value: "internal_itching", label: "Internal Itching" },
  { value: "mucoid_sputum", label: "Mucoid Sputum" },
  {
    value: "history_of_alcohol_consumption",
    label: "History Of Alcohol Consumption",
  },
  { value: "swollen_blood_vessels", label: "Swollen Blood Vessels" },
  { value: "unsteadiness", label: "Unsteadiness" },
  { value: "inflammatory_nails", label: "Inflammatory Nails" },
  { value: "depression", label: "Depression" },
  { value: "fluid_overload", label: "Fluid Overload" },
  { value: "swelled_lymph_nodes", label: "Swelled Lymph Nodes" },
  { value: "malaise", label: "Malaise" },
  { value: "prominent_veins_on_calf", label: "Prominent Veins On Calf" },
  { value: "puffy_face_and_eyes", label: "Puffy Face And Eyes" },
  { value: "fast_heart_rate", label: "Fast Heart Rate" },
  { value: "irritability", label: "Irritability" },
  { value: "muscle_pain", label: "Muscle Pain" },
  { value: "mild_fever", label: "Mild Fever" },
  { value: "yellow_urine", label: "Yellow Urine" },
  { value: "phlegm", label: "Phlegm" },
  { value: "enlarged_thyroid", label: "Enlarged Thyroid" },
  { value: "increased_appetite", label: "Increased Appetite" },
  { value: "visual_disturbances", label: "Visual Disturbances" },
  { value: "brittle_nails", label: "Brittle Nails" },
  { value: "drying_and_tingling_lips", label: "Drying And Tingling Lips" },
  { value: "polyuria", label: "Polyuria" },
  { value: "pain_behind_the_eyes", label: "Pain Behind The Eyes" },
  { value: "typhos", label: "Typhos" },
  { value: "throat_irritation", label: "Throat Irritation" },
  { value: "swollen_extremeties", label: "Swollen Extremeties" },
  { value: "slurred_speech", label: "Slurred Speech" },
  { value: "red_spots_over_body", label: "Red Spots Over Body" },
  { value: "belly_pain", label: "Belly Pain" },
  {
    value: "receiving_blood_transfusion",
    label: "Receiving Blood Transfusion",
  },
  { value: "acute_liver_failure", label: "Acute Liver Failure" },
  { value: "redness_of_eyes", label: "Redness Of Eyes" },
  { value: "rusty_sputum", label: "Rusty Sputum" },
  { value: "abnormal_menstruation", label: "Abnormal Menstruation" },
  {
    value: "receiving_unsterile_injections",
    label: "Receiving Unsterile Injections",
  },
  { value: "coma", label: "Coma" },
  { value: "sinus_pressure", label: "Sinus Pressure" },
  { value: "palpitations", label: "Palpitations" },
  { value: "stomach_bleeding", label: "Stomach Bleeding" },
  { value: "runny_nose", label: "Runny Nose" },
  { value: "congestion", label: "Congestion" },
  { value: "blood_in_sputum", label: "Blood In Sputum" },
  { value: "loss_of_smell", label: "Loss Of Smell" },
];

const symptomMatcher = (text) => {
  return symptoms.filter((s) =>
    s.label.toLowerCase().includes(text.toLowerCase())
  );
};

export default symptomMatcher;
